### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices cuda:0 and cpu!

### ISSUE THREAD

**Issue by ChaosAdmStudent** [Xinjie-Q/GaussianImage#3]
I am just trying to recreate the results by installing all the necessary requirements, getting the dataset in the right directory format and then running the bash script for the kodak dataset. 

I changed CUDA_VISIBLE_DEVICES=0,1 in the script since I only have 2 cuda devices. 

I get the following error when running the script: 

```
Traceback (most recent call last):
  File "GaussianImage/train.py", line 197, in <module>
    main(sys.argv[1:])
  File "GaussianImage/train.py", line 173, in main
    psnr, ms_ssim, training_time, eval_time, eval_fps = trainer.train()
                                                        ^^^^^^^^^^^^^^^
  File "GaussianImage/train.py", line 71, in train
    loss, psnr = self.gaussian_model.train_iter(self.gt_image)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "GaussianImage/gaussianimage_cholesky.py", line 101, in train_iter
    render_pkg = self.forward()
                 ^^^^^^^^^^^^^^
  File "GaussianImage/gaussianimage_cholesky.py", line 94, in forward
    out_img = rasterize_gaussians_sum(self.xys, depths, self.radii, conics, num_tiles_hit,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/gimage/lib/python3.11/site-packages/gsplat/rasterize_sum.py", line 72, in rasterize_gaussians_sum
    return _RasterizeGaussiansSum.apply(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/gimage/lib/python3.11/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/gimage/lib/python3.11/site-packages/gsplat/rasterize_sum.py", line 123, in forward
    torch.ones(img_height, img_width, colors.shape[-1], device=xys.device)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

After checking the devices of the inputs and outputs of the `rasterize_gaussians_sum` function, I can see that the output tensors are all hosted on the CPU even though the input tensors (`self.get_xyz` and `self.get_cholesky_elements`) are on cuda:0 

Unable to fix it by simply moving all output tensors to cuda:0 manually 
```
CUDA error: an illegal memory access was encountered
```

**Comment by Xinjie-Q** [comment]
Hi, could you provide the running command? When I use cuda0, it can still obtain the correct results.
